-- 1. Create visitor_stats table if not exists
CREATE TABLE IF NOT EXISTS public.visitor_stats (
    type text PRIMARY KEY,
    count bigint DEFAULT 0,
    last_reset_date date DEFAULT CURRENT_DATE
);

INSERT INTO public.visitor_stats (type, count, last_reset_date)
VALUES 
    ('daily', 0, CURRENT_DATE),
    ('weekly', 0, CURRENT_DATE),
    ('monthly', 0, CURRENT_DATE)
ON CONFLICT (type) DO NOTHING;

-- 2. Create posts table (for Activities and Knowledge)
CREATE TABLE IF NOT EXISTS public.posts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text, -- Caption for activity, Title for knowledge
    content text, -- HTML content for knowledge
    thumbnail_url text, -- Image for activity/knowledge (legacy single image)
    image_urls text[], -- NEW: Multi-image array for activities
    category text, -- 'activity' or 'knowledge'
    author_id uuid references auth.users(id)
);

-- Add image_urls column if it doesn't exist (for existing tables)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'posts' AND column_name = 'image_urls') THEN
        ALTER TABLE public.posts ADD COLUMN image_urls text[];
    END IF;
END $$;

-- 3. Materials Table (if not exists)
CREATE TABLE IF NOT EXISTS public.materials (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text,
    description text,
    link_url text,
    category text,
    thumbnail_url text,
    likes_count bigint DEFAULT 0,
    author_id uuid references auth.users(id)
);

-- 4. Inquiries Table (NEW)
CREATE TABLE IF NOT EXISTS public.inquiries (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    email text,
    message text not null,
    is_read boolean DEFAULT false
);

-- Enable RLS
ALTER TABLE public.visitor_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- Policies (DROP first to avoid "already exists" errors)

-- Visitor Stats
DROP POLICY IF EXISTS "Public Scan Stats" ON public.visitor_stats;
CREATE POLICY "Public Scan Stats" ON public.visitor_stats FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Update Stats" ON public.visitor_stats;
CREATE POLICY "Public Update Stats" ON public.visitor_stats FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public Insert Stats" ON public.visitor_stats;
CREATE POLICY "Public Insert Stats" ON public.visitor_stats FOR INSERT WITH CHECK (true);

-- Posts
DROP POLICY IF EXISTS "Public Read Posts" ON public.posts;
CREATE POLICY "Public Read Posts" ON public.posts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin Insert Posts" ON public.posts;
CREATE POLICY "Admin Insert Posts" ON public.posts FOR INSERT WITH CHECK (
  (auth.jwt() ->> 'email') = 'sunhak98@naver.com'
);

DROP POLICY IF EXISTS "Admin Update Posts" ON public.posts;
CREATE POLICY "Admin Update Posts" ON public.posts FOR UPDATE USING (
  (auth.jwt() ->> 'email') = 'sunhak98@naver.com'
);

DROP POLICY IF EXISTS "Admin Delete Posts" ON public.posts;
CREATE POLICY "Admin Delete Posts" ON public.posts FOR DELETE USING (
  (auth.jwt() ->> 'email') = 'sunhak98@naver.com'
);

-- Materials
DROP POLICY IF EXISTS "Public Read Materials" ON public.materials;
CREATE POLICY "Public Read Materials" ON public.materials FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Update Likes" ON public.materials;
CREATE POLICY "Public Update Likes" ON public.materials FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Admin Insert Materials" ON public.materials;
CREATE POLICY "Admin Insert Materials" ON public.materials FOR INSERT WITH CHECK (
  (auth.jwt() ->> 'email') = 'sunhak98@naver.com'
);

DROP POLICY IF EXISTS "Admin Update Materials" ON public.materials;
CREATE POLICY "Admin Update Materials" ON public.materials FOR UPDATE USING (
  (auth.jwt() ->> 'email') = 'sunhak98@naver.com'
);

DROP POLICY IF EXISTS "Admin Delete Materials" ON public.materials;
CREATE POLICY "Admin Delete Materials" ON public.materials FOR DELETE USING (
  (auth.jwt() ->> 'email') = 'sunhak98@naver.com'
);

-- Inquiries
DROP POLICY IF EXISTS "Public Insert Inquiries" ON public.inquiries;
CREATE POLICY "Public Insert Inquiries" ON public.inquiries FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Admin Select Inquiries" ON public.inquiries;
CREATE POLICY "Admin Select Inquiries" ON public.inquiries FOR SELECT USING (
  (auth.jwt() ->> 'email') = 'sunhak98@naver.com'
);

-- Storage (images bucket)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public Access Images" ON storage.objects;
CREATE POLICY "Public Access Images" ON storage.objects FOR SELECT
USING ( bucket_id = 'images' );

DROP POLICY IF EXISTS "Admin Upload Images" ON storage.objects;
CREATE POLICY "Admin Upload Images" ON storage.objects FOR INSERT 
WITH CHECK ( bucket_id = 'images' AND auth.role() = 'authenticated' );
